### ISSUE TITLE
[bug] updater not working on macOS + windows

### ISSUE THREAD

**Issue by kyleaupton** [kyleaupton/bucket-browser#32]
#### Describe the bug

The updater is not working on macOS. I have `0.0.1` currently installed, and `0.0.2` is available. Here's the log output:

```
[2024-09-01 16:41:14.790] [info]  App ready
[2024-09-01 16:41:14.842] [info]  (auto-updater) Checking for update
[2024-09-01 16:41:15.537] [info]  (auto-updater) Found version 0.0.2 (url: bucket-browser-macOS-x64-0.0.2.dmg, bucket-browser-macOS-arm64-0.0.2.dmg)
[2024-09-01 16:41:15.538] [info]  (auto-updater) Downloading update from bucket-browser-macOS-x64-0.0.2.dmg, bucket-browser-macOS-arm64-0.0.2.dmg
[2024-09-01 16:41:15.539] [debug] (auto-updater) Checking for macOS Rosetta environment
[2024-09-01 16:41:15.545] [info]  (auto-updater) Checked for macOS Rosetta environment (isRosetta=false)
[2024-09-01 16:41:15.546] [debug] (auto-updater) Checking for arm64 in uname
[2024-09-01 16:41:15.548] [info]  (auto-updater) Checked 'uname -a': arm64=true
[2024-09-01 16:41:15.549] [error] (auto-updater) Error: Error: ZIP file not provided: [
  {
    "url": "https://github.com/kyleaupton/bucket-browser/releases/download/v0.0.2/bucket-browser-macOS-arm64-0.0.2.dmg",
    "info": {
      "url": "bucket-browser-macOS-arm64-0.0.2.dmg",
      "sha512": "aQdm85BuYM8Zt4jn+TTxIc+qM+JJv9Ovk70BJ3qfR+IW/3v8PuysgstFvK/JBSe9VOAHHFd+xl5prql+mFACtg==",
      "size": 101772144
    }
  }
]
    at u (file:///Applications/Bucket%20Browser.app/Contents/Resources/app.asar/dist-electron/main/index-B2Yi6PeP.js:2159:17)
    at c.doDownloadUpdate (file:///Applications/Bucket%20Browser.app/Contents/Resources/app.asar/dist-electron/main/index-B2Yi6PeP.js:8074:30)
    at c.downloadUpdate (file:///Applications/Bucket%20Browser.app/Contents/Resources/app.asar/dist-electron/main/index-B2Yi6PeP.js:7155:21)
    at c.doCheckForUpdates (file:///Applications/Bucket%20Browser.app/Contents/Resources/app.asar/dist-electron/main/index-B2Yi6PeP.js:7128:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by kyleaupton** [comment]
Updater now seems to be working. Tested with `0.0.4` --> `0.0.5` on both macOS and Windows. Here's what I changed:

#### macOS

In `scripts/build.js` I changed `config.mac.target` to `default` (use to be `dmg`). This now means that a zip file will be created and uploaded to the release assets. Apparently electron-builder needs that...?

#### Windows

Windows was complaining the publisher name of the code signing certificate didn't match what the new version's was. The issue is the windows build shouldn't be code signed. It was using the macOS code signing cert because `CSC_LINK` & `CSC_KEY_PASSWORD` were being supplied for windows builds. This is pointless and won't work, windows still claims the app is from an "Unidentified publisher" when installing, so it has zero value add.

The solution was to make sure we weren't "code signing" when building for windows.
